name: Docker Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
      - name: Checkout
        uses: actions/checkout@v6
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build . -tag ghcr.io/gerardo-rojas/skills-publish-docker-images/Stackoverflown:latest
      - name: Publish
        run: |
          docker push ghcr.io/gerardo-rojas/skills-publish-docker-images/Stackoverflown:latest